name: Daily analytics

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * 1" # Every Monday at midnight


jobs:
  run-analytics:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{secrets.PAT}}

      - uses: dart-lang/setup-dart@v1

      - name: Get dependencies
        run: dart pub get

      - name: Run analytics
        run:  dart bin/pub_analytics.dart ./assets/2024_q4 --export

      - name: Git push
        run: git push
      



