name: Daily analytics

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * 1" # Every Monday at midnight


jobs:
  run-analytics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{secrets.PAT}}
      - uses: dart-lang/setup-dart@v1
      - run: |
          dart pub get && dart bin/pub_analytics.dart ./assets/2024_q4 --export && git push
      



