name: Daily analytics

on:
  schedule:
    - cron: "0 0 * * 1" # Every Monday at midnight


jobs:
  run-analytics:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{secrets.PAT}}

      - uses: dart-lang/setup-dart@v1

      - name: Get dependencies
        run: dart pub get

      - name: Run analytics
        run:  dart bin/pub_analytics.dart ./assets/2024_q4 --export

      - name: Git push
        run: |
          git config user.email "eric@ericwindmill.com"
          git config user.name "Eric Windmill"
          git add -A && git commit -m 'check-in weekly analytics' && git push
      



